spring:
  application:
    name: qridaba_backend
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/qridaba_db}
    username: ${SPRING_DATASOURCE_USERNAME:qridaba_user}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:create-drop}
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
        debug: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    use-root-path: true

server:
  address: 0.0.0.0

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration: ${JWT_EXPIRATION:86400000}
      refresh-token:
        expiration: ${JWT_REFRESH_EXPIRATION:604800000}

logging:
  level:
    org:
      springframework:
        security: DEBUG
        mail: DEBUG
    com:
      sun:
        mail: TRACE
    jakarta:
      mail: DEBUG
